#!/usr/bin/python3

print("# generated by create_idt.py - do not edit")
print("# handlers")
print("#include \"boot.h\"")
print("	.global traps")
print(".align 4")
print(".text")
for i in range(0,256):
	print(".global vector%d" %i)
	print("vector%d:" %i)
	if not(i == 8 or (i >= 10 and i <= 14) or i == 17):
		print("	pushl $0")
	print("	pushl $%d" %i)
	print("	jmp alltraps")

#所有的中断都会跳转到这创建中断帧
print("alltraps:")
print("	pushl %ds")
print("	pushl %es")
print("	pushl %fs")
print("	pushl %gs")
print("	pushal")
print(" movw $(SEG_KDATA<<3),%ax")
print("	movw %ax,%ds")
print("	movw %ax,%es")
print("	pushl %esp")
print("	call traps")
print("	addl $4,%esp")

#所有的中断都会返回到这消除中断帧
print("trapret:")
print("	popal")
print("	popl %gs")
print("	popl %fs")
print("	popl %es")
print("	popl %ds")
print("	addl $0x8,%esp")
print("	iret")

print("# vector table")
print(".data")
print(".global vectors")
print("vectors:")
for i in range(0,256):
	print("  .long vector%d" %i)
